# Site settings
title: Adam Fokken
email: adam.fokken@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my github blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamfokken.github.io" # the base hostname & protocol for your site
twitter_username: adamfokken
github_username:  adamfokken

# Build settings
markdown: kramdown
